/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Move file or folder to trash. */
export function trash(path: string): void
/** Move all files and folders to trash. */
export function trashAll(paths: Array<string>): void
